API:
  OPENAI_API_KEY: "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"
DB:
  TIMEOUT: 5
  MONGO_URL: []
  MONGO_USERNAME: jihwan
  MONGO_PASSWORD: 035100

  MONGO_ERROR_LOG_COLLECTION: "error-log"
  MONGO_INFO_LOG_COLLECTION: "info-log"